### ISSUE TITLE
Trouble installing from the Dropbox MSI

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-link#135]
In the 6/6 bug hunt, I was on the Ulna Windows machine, which had a previous version of Scratch Link installed on it, and that version was running, unbeknownst to me.

I used this link to get a new version of Scratch Link: https://www.dropbox.com/s/y222oldv1jgopbw/ScratchLinkSetup-1.1.85.0.zip?dl=0

I ran the installer and everything seemed to work fine, but on the last step of the install, I clicked Finish, with the "Launch Scratch Link" checkbox checked, and the new version failed to start because of a used port.
I exited the running version of Scratch Link and tried re-opening it, thinking that the newly installed version would run, but this only started the older version.
So then I exited Scratch Link again, and tried re-running the installer. This gave me an error "This application requires Windows 10 Creators Update or later." (???)

So I uninstalled Scratch Link from the computer, and ran the installer again. This completed successfully but the last step again failed with the port in use error.  However, there was no running version of Scratch Link, and there was no version of Scratch Link to uninstall. Furthermore the installer would now only give me the "Windows 10 Creators Update" error when I ran it, but I had no other action to perform, since there was no version of Scratch Link on the computer that I could find to uninstall.

At this point I restarted the computer. It started up and launched the new version of Scratch Link at start up. Everything worked fine after this point.

**Comment by cwillisf** [comment]
Nobody has reported this for a while so I'm going to assume it was a temporary problem with that build and/or the individual computer. If anyone sees this again please re-open with as much detail as you can provide. Thanks!

**Comment by karmei** [comment]
Same issue with me. Windows 10 Pro version is 21H2...so, way newer then this Creators update
