### ISSUE TITLE
Not able to connect to Micro:bit on osX

### ISSUE THREAD

**Issue by a-pasquale** [LLK/scratch-link#142]
### Expected Behavior

After installing the scratch-microbit-1.1.0.hex file on the micro:bit, I should be able to connect to Scratch using Scratch Link.

### Actual Behavior

![image](https://user-images.githubusercontent.com/539763/61999289-a1065400-b08b-11e9-9671-12a64283b23d.png)

### Steps to Reproduce

Install scratch-microbit-1.1.0 hex file, start Scratch Link, open Scratch website and add Micro:bit extension.

### Operating System and Browser

Scratch Link: 1.18.827.1749
osX 10.14.5
Chrome browser
Bluetooth enabled

**Comment by benjiwheeler** [comment]
Trying to think of troubleshooting steps. Can you confirm that you are able to connect to other Bluetooth devices?

**Comment by benjiwheeler** [comment]
Is your micro bit powered by a USB cable or a battery pack?

**Comment by a-pasquale** [comment]
Bluetooth is working; I can connect to other devices.
I am powering the microbit with a USB cable.

**Comment by ericrosenbaum** [comment]
Please try updating to the latest version of scratch link (available from scratch.mit.edu/microbit)

**Comment by a-pasquale** [comment]
I just updated again, but no luck. 
Scratch Link 1.18.827.1749 57133af
macOS Version 10.14.5 (Build 18F132)
Thanks for the suggestions.

**Comment by ericrosenbaum** [comment]
@a-pasquale Sorry for the trouble. Based on the info you've provided (thank you!) it looks like the update process failed. You initially had a pre-release version of Scratch Link, from August 2018, and you still have that same version. The current version is `1.1.46`. We have seen a problem where the installer is not able to overwrite pre-release versions. I think what you will need to do is manually remove the old version by deleting it from your applications folder, and run the installer again for the new version.

**Comment by a-pasquale** [comment]
Thanks, that solved it. Much appreciated!
