### ISSUE TITLE
Not connecting to Lego Boost on Windows 10

### ISSUE THREAD

**Issue by ThomasEnzinger** [LLK/scratch-link#163]
### Expected Behavior

I'm trying to connect the Lego BOOST set for my son to https://scratch.mit.edu/boost.

### Actual Behavior

I'm trying to make it work for quite some time now, and actually one time I succeeded. I could control the Lego BOOST motors. So I know my hardware is capable to do the job.
But I since then I was not able to make it work again, and the behavior is quite strange:
When I click 'Start Searching' I can see the search-window (with the image of the BOOST) for a fraction of a second. Then it immediately changes to the screen which tells me '(1) Make sure you have Scratch Link installed and running (2) Check that Bluetooth is enabled'.

### Steps to Reproduce

- Install Scratch Link (I have tried with 1.3.0.0 and with 1.3.10.0)
- Try to add the Lego BOOST extension (https://scratch.mit.edu/projects/editor)

### Operating System and Browser

- Windows 10 Pro, Build 18363
- Chrome 80.0.3987.149    and   Firefox 74
- Scratch Link 1.3.0.0   and    1.3.10.0

**Comment by BryceLTaylor** [comment]
Issues with your own personal setup for a device are best addressed to contact us: https://scratch.mit.edu/contact-us/ 

However, @ThomasEnzinger it may be worth going into your OS's bluetooth settings and "Forget" the boost and try again.  Sometimes your OS prevents Scratch Link from finding the device.
