### ISSUE TITLE
Documentation on how to debug to help fix mac bugs

### ISSUE THREAD

**Issue by grantkemp** [LLK/scratch-link#164]
Please can you kindly share some basic debugging instructions or what I need to do in order to fix the Mac OS bug where it doesn't connect. 

Happy to contribute the swift code to fix it the connection to lego boost, however I am not sure what I should be looking for to determine that it's connected.

**Comment by BryceLTaylor** [comment]
@grantkemp can you please describe the issue that you're seeing and how to reproduce it?

**Comment by BryceLTaylor** [comment]
I'm going to close this issue since it is not referencing a specific issue.  Feel free to open it again with a description of the issue you're seeing including reproduction steps.
