### ISSUE TITLE
No device found when using DNS masquerade

### ISSUE THREAD

**Issue by francesco-vannini** [LLK/scratch-link#166]
### Expected Behavior

The BBC Microbit should be found and connected via BT using the Scratch Link

### Actual Behavior

No device is found despite several refreshes

### Steps to Reproduce

Set the DNS to use either OpenDNS or use the default DNS of the router which in turn uses OpenDNS :)

Once the DNS is set to my ISP directly or via my router the problem disappears.

### Operating System and Browser

Windows 10.0.18363 Build 18363 using Scratch desktop or Chrome 80.0.3987.163 (Official Build) (64-bit)
Scratch Link 1.3.0 (7ef11a6) Win32NT

**Comment by apple502j** [comment]
Maybe read #137 ?

**Comment by francesco-vannini** [comment]
Hi @apple502j the issue is definitely related to that so wrong title from me. As in #137 this link https://scratch.mit.edu/discuss/post/3597312/ seems to address the problem too.

It would be nice to document this issue at least within the FAQ of scratch.mit.edu/microbit as I'm sure many will have a similar setup to mine.

I created a "host override" within DNS Resolver of my Pfsense and that solved the issue throughout the network.
Editing the local host file (C:\Windows\System32\Drivers\etc\hosts) also works.
![image](https://user-images.githubusercontent.com/16068311/79126349-0e841d00-7da0-11ea-84b8-d77db864843c.png)

I guess the issue's title should change to **No device found when using DNS masquerade**
