### ISSUE TITLE
Certificate revoked: Scratch Link won't work on growing number of computers

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-link#175]
### Expected Behavior

Scratch Link should work on all supported computers.

### Actual Behavior

One of the certificates that Scratch Link uses has been revoked. As computers update their certificate information, more and more computers will register that the certificate has been revoked. Any computer which has registered the certificate as revoked will prevent Scratch Link from working correctly.

### Steps to Reproduce

1. Install any version of Scratch Link
2. Run Scratch 3.0 (on the web site or in the app)
3. Attempt to use a hardware extension such as micro:bit, a LEGO kit, etc.

If your computer is affected, Scratch will behave as if Scratch Link is not running or cannot be contacted. If you're running in a browser, you might see a certificate error in your browser's JavaScript console or network window.

### Operating System and Browser

This affects both macOS and Windows using any browser.

**Comment by microbit-mark** [comment]
Several micro:bit users have now reported this too. Thanks for diagnosing the issue and providing a fix. Let me know if you need us to do any testing.

**Comment by cwillisf** [comment]
This fix will be in version 1.3.54 or higher, or version 1.4.0 or higher.

**Comment by microbit-mark** [comment]
Does 1.3.54 or 1.4.0 have a release date, or is there a binary and can provide to users?

**Comment by cwillisf** [comment]
No release date quite yet, but it's in the testing phase. If we don't find any big problems we'll be releasing it very soon.

**Comment by BryceLTaylor** [comment]
This has been released for direct download on our site and has been submitted to the stores for approval.

**Comment by tim-gp** [comment]
Great, thanks @BryceLTaylor - I'll get the 8 year old back to coding tomorrow then.
