### ISSUE TITLE
Micro:bit disconnects after few seconds

### ISSUE THREAD

**Issue by smarx80** [LLK/scratch-link#190]
### Expected Behavior

After connecting via BT with Scratch Link active to my PC (Win10), I'm expecting to have my micro_bit connected for all the time.

### Actual Behavior

After connecting via BT with Scratch Link active to my PC (Win10), my micro:bits are disconnecting. 

### Operating System and Browser

Windows 10, latest version of scratch link, latest bootloader of microbit (v1), latest HEX for scratch-microbit firmware.

**Comment by apple502j** [comment]
micro:bit uses BLE, not BT. (BT is only used for EV3.)

**Comment by smarx80** [comment]
> 
> 
> micro:bit uses BLE, not BT. (BT is only used for EV3.)

thanks apple502j for your clarification, although I don't know how it could help. Whether it's the bluetooth or bluetooth low energy, the problem is that the micro:bit disconnects from scratch link after 1-2 seconds. From micro:bit support says that it shouldn't do that, and to ask here to identify the possible bug. I've tried disabling energy saving from bluetooth devices in windows device manager, but nothing has changed. Thanks for any suggestions.

**Comment by smarx80** [comment]
Maybe I have solved! As in so many situations, the answer was much simpler than expected. I had paired the devices via windows bluetooth, because I thought it was necessary for scratch link to detect them. Removed from there, everything worked properly. Thanks. Simone.

**Comment by BryceLTaylor** [comment]
I'm glad you figured it out!
