### ISSUE TITLE
Scratch Link no longer able to locate micro:bit

### ISSUE THREAD

**Issue by microbit-mark** [LLK/scratch-link#201]
Multiple users reporting that they cannot connect micro:bit in a variety of OS and browser combinations. Maybe related to #198 

### Expected Behavior

micro:bit is connected to Scratch

### Actual Behavior

micro:bit is not found

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

Steps to reproduce the behaviour:
Follow steps in https://scratch.mit.edu/microbit

### System Details
Windows 11 Home, Version 10.0.22000 Build 2200 Chrome 98, Edge, Firefox
Windows 10 Home Chrome 98, Edge
macOS11 Chrome 98

micro:bit V1 DAPLink 0249 and V2 DAPLink 0255

Scratchink 1.3.67

No antivirus or firewall that would block the port

Same behaviour in Mac offline app

**Screenshots**
![Image 2022-02-09 at 11 17 18 am](https://user-images.githubusercontent.com/31242877/153190210-34d4a6f5-eb9d-46b2-85ab-5eeed2322893.jpg)

![Image 2022-02-09 at 11 17 39 am](https://user-images.githubusercontent.com/31242877/153190196-d3df3c8a-db2b-43ec-b02e-6ed5dc025650.jpg)

**Comment by apple502j** [comment]
See #200 - TL;DR: The program had a terrible design in terms of security, like [Spotify did back in 2017](https://www.feistyduck.com/bulletproof-tls-newsletter/issue_29_cisco_and_spotify_ship_private_keys_in_applications).

**Comment by microbit-mark** [comment]
Thanks, @apple502j, after reading through, I understand the issues are related.

As a workaround using the `--ignore-certificate-errors flag ` in chrome resolves the issue for me on Windows 10, but I would not want to recommend this for people in general use.

<img width="921" alt="image" src="https://user-images.githubusercontent.com/31242877/153221555-85b24fbb-2510-4eb3-b333-109fdc0c278d.png">

**Comment by BrickEducation** [comment]
also DESKTOP scratch have scratclink problem

**Comment by BryceLTaylor** [comment]
Closing in favor of #200
