### ISSUE TITLE
ScratchLink no longer works  

### ISSUE THREAD

**Issue by BrickEducation** [LLK/scratch-link#202]
### Expected Behavior
scratchlink worked fine until yesterday BUT today nothing at all. This happens on all my 10 PCs and on the school PCs (win 10, hp or lenovo). It is therefore impossible to use wedo2 and not even Lego boost or micro: bit

### Actual Behavior
A) An allert says that scratchlink not work, not installed or bluetooth not active. BUT with wedo2 native app everything works perfectly!!

B) Unistalling scratchlink and REinstalling there a two behavior:
1) Installing process stop and ask to update windows at win Creator version (an old version of window, we are using newer version of Win10, and all fine until today!)
2) If installing process is finalized Scratchlink does not work (go to A)

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

1) Switch on PC
2) Run Scratchlink
3) Run Scratch desktop (3.25 or 3.28 is the same) or scratch online (we tried both Chrome and Edge)
4) upload WEDO2 Esxtension (or any other that requires Scratchlnk)
5) Try to find the HUB
6) Fail : allert says that scratchlink not work, not installed or bluetooth not active.

### System Details
Win 10, 21H1 build SO 19043.4526  or  Win10 20H2 build SO 19042.1165 (same problem)
Scratchlink 1.3.67.0
with Scratch Desktop 3.25 (or 3.28 same problem)

or with Scratch online (Chrome or Edge same problem)
![image](https://user-images.githubusercontent.com/99341110/153237228-3ac3d4ea-ddeb-4d6a-a927-aa27da674a5e.png)

**Comment by colbygk** [comment]
Related: #200

**Comment by BrickEducation** [comment]
A rapid alternative while ScratchLink is on "repair mode" for all teachers having robotic courses at school in these day
https://www.brickeducation.it/scratchlink-non-funziona/

**Comment by BryceLTaylor** [comment]
Tracking this work in #200
