### ISSUE TITLE
No Devices Found  on Mac OS 12.2.1 to connect Wedo 2.0  device LPF2 Smart Hub 2 I/O

### ISSUE THREAD

**Issue by wenchao-cui** [LLK/scratch-link#205]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

1. LEGO Wedo 2.0 App:  Connect the device OK
2. LEGO Wedo 2.0 App:  Disconnect bluetooth device.
3. Open Scratch Link
4. Open Scratch
5. Add Extension: Wedo 2.0
6. Start Searching 
7. Press the button on the device
8. No Devices Found

![ScreenShot 2022-02-26 22 57 19](https://user-images.githubusercontent.com/75101043/155847756-74f57056-b7b4-4154-a86a-6e3eaab915f2.png)

### Operating System and Browser

Mac OS 12.2.1 (21D62) 
MacBook Air (13-inch, Early 2015)
Bluetooth Chip:  BCM_20702B0

Scratch 3.29.1  AppStore
Scratch Link 1.4.3 f78273b macOS Version 10.16 (Build 21D62)

I collected the network packets:
(1)  Scratch  --->  Scratch Link
GET /scratch/ble HTTP/1.1
Host: 127.0.0.1:20111
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Scratch/3.29.1 Chrome/94.0.4606.81 Electron/15.3.1 Safari/537.36
Upgrade: websocket
Origin: file://
Sec-WebSocket-Version: 13
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN
Sec-WebSocket-Key: Lqy7/7NJpj18cHltzZgcew==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits

(2)  Scratch  <---  Scratch Link
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: hqBGgYStx87UxW/gKrjgBkHs9m8=
Content-Length: 0

(3)  Scratch  --->  Scratch Link  (websocket data)
{"jsonrpc":"2.0","method":"discover","params":{"filters":[{"services":["00001523-1212-efde-1523-785feabcd123"]}],"optionalServices":["00004f0e-1212-efde-1523-785feabcd123"]},"id":0}

(4)  Scratch  <---  Scratch Link
{"result":null,"jsonrpc":"2.0","id":0}

---------------------------------------------------
BUT,   on the same computer , LEGO Wedo 2.0 App can connect the device, with no problem. 
The Connected Device Name:  LPF2 Smart Hub 2 I/O

![ScreenShot 2022-02-26 22 49 02](https://user-images.githubusercontent.com/75101043/155847602-9d85b323-a27c-4c30-ac9c-d618b111dc2e.png)

**Comment by BryceLTaylor** [comment]
This appears to be the same issue as https://github.com/LLK/scratch-link/issues/198

**Comment by wenchao-cui** [comment]
邮件已收到，这是自动回复
