### ISSUE TITLE
Makefile doesn't accept folders with spaces in the name

### ISSUE THREAD

**Issue by evhan55** [LLK/scratch-link#66]
**Expected**:

Running `make` doesn't give errors.

**Observed**:

When running `make` in the `macOS` directory, it would error out if a folder name in one of the paths containing the repo had a space in the name.  Example folder name: `git repos`.

**Workaround**:

Changing the folder from `git repos` to `repos` lets the `make` script run to completion, but perhaps this can be fixed to not need that as an enhancement in the future.

**Comment by cwillisf** [comment]
This was added to the repository README.md a while ago but I forgot to close this issue. Closing it now.
