### ISSUE TITLE
After connecting EV3/SPIKE Prime on windows, can't reconnect without first un-pairing

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-link#94]
Once I have connected to an EV3, and then disconnected, and then restarted Scratch Link (due to the crash in https://github.com/LLK/scratch-link/issues/93), when I attempt to connect again, the EV3 never appears in the scan.

The only reliable way I have found to be able to find and connect to the EV3 is to use the Windows Bluetooth settings to unpair the EV3 (i.e. "remove this device"). After I do that, the EV3 appears immediately in the scan, and I am able to connect.

Scratch Link 1.1.9.0
Chrome 70
Windows 10 Pro 1803 build 17134.345

**Comment by evhan55** [comment]
This is also true for the LEGO SPIKE Prime.
